name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
      REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build
      env:
        REACT_APP_STRAVA_CLIENT_ID: ${{ secrets.REACT_APP_STRAVA_CLIENT_ID }}
        REACT_APP_STRAVA_CLIENT_SECRET: ${{ secrets.REACT_APP_STRAVA_CLIENT_SECRET }}

    - name: Check Build Output
      run: grep REACT_APP_STRAVA_CLIENT_ID build/static/js/*.js || echo "Client ID not found in build output"

    - name: Debug
      run: |
        echo "Client ID is set: ${{ env.REACT_APP_STRAVA_CLIENT_ID != '' }}"
        echo "Client Secret is set: ${{ env.REACT_APP_STRAVA_CLIENT_SECRET != '' }}"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
